Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-04, with the labels that each got.

#1317 FUSETOOLS-2899 - provide online configuration for camel version to
  configuration/defaultVersionToSelect.properties
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/DefaultVersions.java
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: PRIO, REVIEW DONE

#1319 FUSETOOLS-2901 - New UI test for checking project creation
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/SingleFuseProjectTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/utils/FuseProjectDefinition.java
Labels: REVIEW DONE

#1321 FUSETOOLS-2897 - replace R0 by GA in Fuse names
  configuration/camelVersionToDisplayName.properties
Labels: READY FOR MERGE

#1327 FUSETOOLS-2905 - Fix Camel version for 6.2.1 R8
  configuration/camel2bom.properties
  configuration/camelVersionToDisplayName.properties
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/CamelForFuse6ToBomMapper.java
Labels: READY FOR MERGE

#1190 FUSETOOLS-2697: Execute Fuse UI smoke tests after each PR
  pom.xml
  uitests/README.md
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml
Labels: REVIEW DONE

#1322 FUSETOOLS-2908 - Update cheat sheet after new wizard refactor
  core/plugins/org.fusesource.ide.cheatsheets/content/createCamelProject.xml
Labels: REVIEW DONE

#1323 FUSETOOLS-2909 - remove question mark at end of Spring Boot template
  editor/plugins/org.fusesource.ide.projecttemplates/OSGI-INF/l10n/bundle.properties
Labels: REVIEW DONE

#1325 FUSETOOLS-2896 - Remove old OSGI Service Component registration
  core/plugins/org.fusesource.ide.camel.model.service.impl/META-INF/MANIFEST.MF
Labels: REVIEW DONE

#1329 FUSETOOLS-2899 - set back config to master branch
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: REVIEW DONE

#1326 FUSETOOLS-2907 - Provide more precise Bom Mapping for manually entered
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
  core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtilsTest.java
Labels: READY FOR REVIEW

#1328 FUSETOOLS-2840 - fixed wrong validation if verify version is canceled
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java
Labels: READY FOR MERGE

#1335 FUSETOOLS-2806: UI Tests - Extend 'Camel catalog' testing util structure
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
Labels: READY FOR MERGE

#1340 FSUEDOC-2433 fix context.xml file
  core/plugins/org.fusesource.ide.help/contexts.xml
Labels: READY FOR MERGE

#1332 FUSETOOLS-2890: Create UI test for "Switching runtime types does not …
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardWithFuseRequirementsTest.java
Labels: READY FOR MERGE

#1342 FUSETOOLS-2908 - Update description of cheatsheet
  core/plugins/org.fusesource.ide.cheatsheets/content/createCamelProject.xml
Labels: PRIO, READY FOR REVIEW

#1351 added script to change eclipse versions
  changeEclipse.sh
Labels: PRIO, READY FOR MERGE

#1347 FUSETOOLS-2879 - Filter Runtime types in drop-down
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/KarafRuntimeFilter.java
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/RuntimeViewerFilter.java
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/WildflyRuntimeFilter.java
  editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/wizards/pages/filter/KarafRuntimeFilterTest.java
  editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/wizards/pages/filter/WildflyRuntimeFilterTest.java
Labels: READY FOR MERGE, REVIEW DONE

#1348 FUSETOOLS-2879 - filter runtime in "New Runtime" wizard
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
Labels: READY FOR MERGE, REVIEW DONE

#1349 FUSETOOLS-2924 - workaround upstream inconsistency for zipFile
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/cache/CamelModel.java
  core/plugins/org.fusesource.ide.camel.model.service.impl/src/org/fusesource/ide/camel/model/service/internal/CamelModelPatcher.java
Labels: READY FOR MERGE, REVIEW DONE

#1354 FUSETOOLS-2940 - Ensure users don't think runtime selection is mandatory
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/internal/Messages.java
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/l10n/messages.properties
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardWithFuseRequirementsTest.java
Labels: READY FOR REVIEW
