Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-09, with the labels that each got.

#1459 FUSETOOLS-3070 - Fix 'FuseOnOpenShiftTest'
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/ContextMenuHasItem.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/OpenShiftExplorer.java
Labels: READY FOR MERGE

#1460 FUSETOOLS-3022 : switch back to master branch for configuration files
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: PRIO, READY FOR REVIEW

#1463 FUSETOOLS-2799 - explicitly set dependency on javax.xml
  core/plugins/org.fusesource.ide.foundation.ui/META-INF/MANIFEST.MF
  core/plugins/org.fusesource.ide.imports/META-INF/MANIFEST.MF
  jmx/plugins/org.fusesource.ide.jmx.camel/META-INF/MANIFEST.MF
  jmx/plugins/org.fusesource.ide.jmx.commons/META-INF/MANIFEST.MF
  transformation/plugins/org.jboss.tools.fuse.transformation.core/META-INF/MANIFEST.MF
  transformation/plugins/org.jboss.tools.fuse.transformation.editor/META-INF/MANIFEST.MF
  transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/META-INF/MANIFEST.MF
  transformation/tests/org.jboss.tools.fuse.transformation.core.tests/META-INF/MANIFEST.MF
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
Labels: READY FOR MERGE

#1461 FUSETOOLS-3004 - fixing rest DSL context ID from help
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DocumentationSection.java
Labels: READY FOR MERGE

#1468 Revert "FUSETOOLS-2799 - explicitly set dependency on javax.xml"
  core/plugins/org.fusesource.ide.foundation.ui/META-INF/MANIFEST.MF
  core/plugins/org.fusesource.ide.imports/META-INF/MANIFEST.MF
  jmx/plugins/org.fusesource.ide.jmx.camel/META-INF/MANIFEST.MF
  jmx/plugins/org.fusesource.ide.jmx.commons/META-INF/MANIFEST.MF
  transformation/plugins/org.jboss.tools.fuse.transformation.core/META-INF/MANIFEST.MF
  transformation/plugins/org.jboss.tools.fuse.transformation.editor/META-INF/MANIFEST.MF
  transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/META-INF/MANIFEST.MF
  transformation/tests/org.jboss.tools.fuse.transformation.core.tests/META-INF/MANIFEST.MF
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
Labels: PRIO, READY FOR MERGE

#1455 updated target platform to latest versions
  targetplatform/fuse-jbosstools.target
Labels: READY FOR MERGE, REVIEW DONE

#1464 FUSETOOLS-3019 - rename server adapter from 7.0 to 7+
  servers/plugins/org.fusesource.ide.server.fuse.core/OSGI-INF/l10n/bundle.properties
Labels: READY FOR MERGE, REVIEW DONE

#1470 FUSETOOLS-3074 - switch back config to master branch
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: READY FOR MERGE, REVIEW DONE

#1465 FUSETOOLS-3084 - Support pure CDATA in attributes
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/withCDATA.xml
Labels: READY FOR MERGE, REVIEW DONE

#1469 FUSETOOLS-2945 - use 7.1 GA version for wsdl2rest libraries
  editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
Labels: READY FOR MERGE, REVIEW DONE

#1472 FUSETOOLS-3088 - fix issues when IDs on Rest Elements are changed
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelContextElement.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/restconfiguration/RestEditorTestIT.java
Labels: READY FOR MERGE

#1476 FUSETOOLS-2462 - integrating Context help on Global Config page
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DocumentationSection.java
Labels: READY FOR MERGE
