Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-03, with the labels that each got.

#1294 added the syndesis version properties file as preparation for further…
  configuration/igniteVersionToDisplayName.properties
Labels: READY FOR REVIEW

#1263 FUSETOOLS-2613 - Create structure for using different versions of Camel catalog in tests
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
  uitests/plugins/org.jboss.tools.fuse.reddeer/plugin.xml
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelCatalogConfiguration.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelCatalogRequirement.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/PaletteViewExt.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogDefaultTest.java
Labels: READY FOR MERGE

#1289 FUSETOOLS-2689: UI Tests - Try to manipulate with routes via Jolokia
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/JMXNavigator.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/Message.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/MessagesView.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JolokiaManipulationTest.java
Labels: READY FOR MERGE

#1291 FUSETOOLS-2735: Create a new test for Verify button in New Fuse Integ…
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/LabelContainsText.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIntegrationProjectWizard.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectVerifyBTNTest.java
Labels: READY FOR MERGE

#1296 FUSETOOLS-2847: UI Tests - Fix SupportedCamelVersions test
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIntegrationProjectWizard.java
Labels: READY FOR MERGE

#1306 FUSETOOLS-2812 - remove tp3 version from syndesis config file
  configuration/igniteVersionToDisplayName.properties
Labels: PRIO, READY FOR REVIEW

#1307 FUSETOOLS-2866 - Update image name from jboss-fuse-7 to fuse7
  editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7/.settings/fusetooling/Deploy %%%PLACEHOLDER_PROJECTNAME%%% on OpenShift.launch
Labels: READY FOR MERGE

#1308 FUSETOOLS-2660 - upgrade internally Camel from 2.20.2 to 2.21.0
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
  core/plugins/org.fusesource.ide.camel.model.service.impl/.classpath
  core/plugins/org.fusesource.ide.camel.model.service.impl/META-INF/MANIFEST.MF
  core/plugins/org.fusesource.ide.camel.model.service.impl/build.properties
  core/plugins/org.fusesource.ide.camel.model.service.impl/pom.xml
  core/tests/org.fusesource.ide.camel.model.service.impl.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/internal/CamelServiceCatalogLoadingIT.java
Labels: READY FOR REVIEW

#1312 FUSETOOLS-2877 - Fix disablement of Camel version drop down
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
Labels: READY FOR MERGE

#1311 FUSETOOLS-2885 - Improve texts in New Fuse Integration wizard
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/internal/Messages.java
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/l10n/messages.properties
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardTemplatePage.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/dialog/WhereToFindMoreTemplatesMessageDialog.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIntegrationProjectWizardAdvancedPage.java
Labels: PRIO, REVIEW DONE
