Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-06, with the labels that each got.

#1372 FUSETOOLS-2617: UI Tests - extend CamelEditorTest - components creation
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorAdditionTest.java
Labels: READY FOR MERGE

#1392 FUSETOOLS-3003 - updating labels/text per docs suggestions
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/rest/RestElementPropertiesSection.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/rest/RestVerbElementPropertiesSection.java
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/OSGI-INF/l10n/bundle.properties
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/src/org/fusesource/ide/wsdl2rest/ui/internal/i10n/messages.properties
Labels: READY FOR MERGE

#1391 FUSETOOLS-2943 - make wsdl2rest wizard top level
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/plugin.xml
Labels: READY FOR MERGE

#1390 FUSETOOLS-2948 - Include Camel LSP client
  editor/features/org.fusesource.ide.camel.editor.feature/feature.xml
Labels: READY FOR MERGE

#1379 rethrow interrupt in catched interruptedexception
  editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java
Labels: READY FOR MERGE

#1394 updated Linux Photon Launch config
  targetplatform/JBossTools Photon Linux x86_64.launch
Labels: READY FOR MERGE

#1343 FUSETOOLS-2667: UI Tests - Fix test ConfigurationsEditorDataFormatsTest
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/TreeHasItem.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelDataFormatDialog.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEndpointDialog.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/ConfigurationsEditor.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorDataFormatTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorEndpointTest.java
Labels: REVIEW DONE

#1397 JBDS-4706 rename JBDS to Red Hat Developer...
  core/plugins/org.fusesource.ide.help/RiderCamelDebugger.html
  core/plugins/org.fusesource.ide.help/RiderDevPart.html
  core/plugins/org.fusesource.ide.help/RiderTutorialCreate.html
  core/plugins/org.fusesource.ide.help/RiderTutorialSetup.html
  core/plugins/org.fusesource.ide.help/RiderTutorialTrace.html
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/LicenseTest.java
Labels: REVIEW DONE

#1396 FUSETOOLS-2980 - reset selection of Rest Element & Rest operation
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/restconfiguration/RestEditorTestIT.java
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/rest-camelContext.xml
Labels: READY FOR MERGE

#1400 FUSETOOLS-2985 - embed Fuse 7 Camel Catalog;...
  core/features/org.fusesource.ide.core.feature/feature.xml
Labels: READY FOR MERGE

#1403 FUSETOOLS-3004 - display rest tab doc page if editor selected is Rest…
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DocumentationSection.java
Labels: REVIEW DONE

#1407 FUSETOOLS-3018 - added Red Hat GA repo to syndesis templates pom.xml
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/pom.xml
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/pom.xml
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/pom.xml
Labels: PRIO, READY FOR REVIEW

#1412 FUSETOOLS-3018 - also provide Red Hat GA repo as pluginRepository
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/pom.xml
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/pom.xml
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/pom.xml
  syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/SyndesisExtensionProjectCreatorRunnableIT.java
Labels: READY FOR MERGE

#1415 FUSETOOLS-2944 - added checks to prevent NPE in MavenUtils, fixes #1414
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/MavenUtils.java
  editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/utils/MavenUtilsTest.java
Labels: READY FOR MERGE
