Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-05, with the labels that each got.

#1365 FUSETOOLS-2967 - Fix UI tests in PR job
  pom.xml
Labels: READY FOR MERGE

#1367 FUSETOOLS-2969 - Fix 'SingleFuseProjectTest'
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/SingleFuseProjectTest.java
Labels: READY FOR MERGE

#1366 FUSETOOLS-2276 - Incorporate 'MarkersRemoverValidatorIT.checkMarkers'…
  core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validator/marker/MarkersRemoverValidatorIT.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/routeWithValidationErrorOnGlobalElements.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/routeWithValidationFixedOnGlobalElements.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProblemsViewTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/suite/SmokeTests.java
Labels: READY FOR MERGE

#1341 FUSETOOLS-2904: Adjust UI Deployment tests for Fuse 7.0.0
  uitests/plugins/org.jboss.tools.fuse.reddeer/resources/.ssh7/known_hosts
  uitests/plugins/org.jboss.tools.fuse.reddeer/resources/hostkey_new/host.key
  uitests/plugins/org.jboss.tools.fuse.reddeer/resources/hostkey_old/host.key
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/runtime/impl/ServerKaraf.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DeploymentTest.java
Labels: REVIEW DONE

#1370 FUSETOOLS-2972 - Update RedDeer version to 2.1.1
  uitests/README.md
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
Labels: READY FOR MERGE, REVIEW DONE

#1361 FUSETOOLS-2595: UI Tests - Improve Camel Editor tests with xpath validation on underlayer XML file
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java
Labels: READY FOR MERGE

#1336 FUSETOOLS-2804: UI Tests - Create a new 'quick' test for component 'Properties view'
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditor.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/FusePropertiesView.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogComponentsTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogDefaultTest.java
Labels: READY FOR MERGE

#1374 FUSETOOLS-2276 - Fix error with ProblemsViewTest
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProblemsViewTest.java
Labels: PRIO, REVIEW DONE

#1376 FUSETOOLS-2978 - avoid Widget is disposed when accessing Camel project
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
Labels: PRIO, READY FOR MERGE

#1369 FUSETOOLS-2951 - remove no more used/invalid repositories from top-level
  pom.xml
Labels: READY FOR MERGE

#1377 FUSETOOLS-2973 - workaround to avoid random failure during test
  editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java
Labels: PRIO, REVIEW DONE

#1371 FUSETOOLS-2964 - fix data transformation for Fuse 7.0+
  transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdater.java
  transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterForManifestIT.java
  transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterForPomIT.java
  transformation/tests/org.jboss.tools.fuse.transformation.editor.tests/src/test/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterTest.java
Labels: REVIEW DONE

#1338 FUSETOOLS-2887: Create a new test for Rest DSL editor
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/ProjectType.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditorPreferences.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/RESTEditor.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.classpath
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.project
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.settings/org.eclipse.core.resources.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.settings/org.eclipse.jdt.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.settings/org.eclipse.m2e.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.settings/org.eclipse.pde.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.settings/org.eclipse.wst.common.component
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.settings/org.eclipse.wst.common.project.facet.core.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/.settings/org.eclipse.wst.validation.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/pom.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/main/java/taskmanager/Task.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/main/java/taskmanager/TaskManager.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/main/java/taskmanager/TaskManagerResponse.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/main/resources/log4j.properties
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/test/java/taskmanager/GreetingsTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/test/java/taskmanager/TaskManagerTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.classpath
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.project
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.settings/org.eclipse.core.resources.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.settings/org.eclipse.jdt.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.settings/org.eclipse.m2e.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.settings/org.eclipse.pde.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.settings/org.eclipse.wst.common.component
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.settings/org.eclipse.wst.common.project.facet.core.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/.settings/org.eclipse.wst.validation.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/pom.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/main/java/taskmanager/Task.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/main/java/taskmanager/TaskManager.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/main/java/taskmanager/TaskManagerResponse.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/main/resources/META-INF/spring/camel-context.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/main/resources/log4j.properties
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/test/java/taskmanager/GreetingsTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/test/java/taskmanager/TaskManagerTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.classpath
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.project
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/fusetooling/Deploy rest-springboot on OpenShift.launch
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/org.eclipse.core.resources.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/org.eclipse.jdt.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/org.eclipse.m2e.core.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/org.eclipse.wst.common.component
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/org.eclipse.wst.common.project.facet.core.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/org.eclipse.wst.validation.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/.settings/org.hibernate.eclipse.console.prefs
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/pom.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/java/taskmanager/Application.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/java/taskmanager/Task.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/java/taskmanager/TaskManager.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/java/taskmanager/TaskManagerResponse.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/resources/META-INF/spring/camel-context.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/resources/application.properties
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/resources/logback.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/test/java/taskmanager/GreetingsTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/test/java/taskmanager/TaskManagerTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RESTEditorTest.java
Labels: READY FOR MERGE

#1382 FUSETOOLS-2955 - Fix camel version databinding when selecting a Runtime
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
Labels: PRIO, REVIEW DONE

#1381 FUSETOOLS-2956 - switch back online config files to master branch
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: REVIEW DONE

#1383 FUSETOOLS-2990 - close wizard dialog at end of test
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/actions/ui/SwitchCamelVersionWizardIT.java
Labels: REVIEW DONE

#1387 FUSETOOLS-3000 - updating wsdl2rest wizard name
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/META-INF/MANIFEST.MF
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/OSGI-INF/l10n/bundle.properties
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/build.properties
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/plugin.xml
Labels: READY FOR MERGE

#1344 FUSETOOLS-2606: Create UI test for language / dataformats properties
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/MavenDependency.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorDataFormatTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorLanguageTest.java
Labels: READY FOR MERGE

#1363 FUSETOOLS-2612: UI Tests - Beans test checking for initialization of wizard with package name and classname
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/FilteredSelectionDialog.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorBeanTest.java
Labels: READY FOR MERGE

#1386 FUSETOOLS-2993 - embed missing icon for wsdl 2 rest wizard
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/build.properties
Labels: READY FOR MERGE

#1385 FUSETOOLS-2965 - use Fuse 7 version for wsdl2rest dependencies
  editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
Labels: READY FOR MERGE

#1380 FUSETOOLS-2963 - reactivate tests with Community version
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCBRIT.java
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCXFCodeFirstIT.java
Labels: READY FOR MERGE

#1378 FUSETOOLS-2981 - adding new launch config for Windows
  targetplatform/JBossTools Photon Windows x86_64.launch
Labels: READY FOR MERGE
