Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-11, with the labels that each got.

#1478 FUSETOOLS-2869 - adding more dependencies via wsdl2rest wizard
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/component/wizard/ComponentManager.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/AddComponentDependencyRunnable.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/src/org/fusesource/ide/wsdl2rest/ui/wizard/Wsdl2RestWizard.java
  editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
  editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/component/wizard/ComponentManagerTest.java
  editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/META-INF/MANIFEST.MF
  editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/src/main/java/org/fusesource/ide/wsdl2rest/ui/tests/integration/Wsdl2RestWizardIT.java
Labels: READY FOR REVIEW

#1492 Fusetools 3169 run as debug as local camel fornew fuse bom
  editor/plugins/org.fusesource.ide.launcher.ui/META-INF/MANIFEST.MF
  editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/propertytester/CamelLocalLaunchPropertyTester.java
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
Labels: READY FOR MERGE

#1487 FUSEQE-2172 - Add test for check import of a project from fuse-apicur…
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/ImportFromArchiveWizard.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/ImportFromArchiveWizardFirstPage.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseApicuritoGeneratorTest.java
Labels: REVIEW DONE

#1479 FUSETOOLS-3093: Improve naming of parameterized test CamelCatalogComponentsTest
  uitests/README.md
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/PaletteViewExt.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogComponentsTest.java
Labels: READY FOR MERGE, REVIEW DONE

#1489 FUSETOOLS-3156: Provide Ui test covering usecase in FUSETOOLS-2997
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLAdvancedPage.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelRestDSLFromWSDLWizardTest.java
Labels: READY FOR MERGE, REVIEW DONE
