Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-08, with the labels that each got.

#1437 FUSETOOLS-3052 - Support typing "displayed name" of camel version
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectVerifyBTNTest.java
Labels: READY FOR MERGE

#1435 FUSETOOLS-3007 - New UI test for Forge projects
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/ForgeOption.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/ForgeConsoleHasText.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/ForgeConsoleView.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ForgeProjectsTest.java
Labels: READY FOR MERGE

#1439 FUSETOOLS-2898 - addressing scroll bars
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
Labels: READY FOR MERGE

#1444 FUSETOOLS-3045 - UI Tests - Adapt ''NewFuseIgniteProjectTest" to new …
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIgniteExtensionProjectSecondPage.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIgniteExtensionProjectWizard.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseIgniteExtWizardTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseIgniteProjectTest.java
Labels: REVIEW DONE

#1446 FUSETOOLS-3046 - some refactoring clean-up
  editor/plugins/org.fusesource.ide.camel.editor/META-INF/MANIFEST.MF
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/AddRestConfigurationAction.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/AddRestElementAction.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/AddRestOperationAction.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/DeleteRestConfigurationAction.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/DeleteRestElementAction.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/DeleteRestOperationAction.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/RestEditorAction.java
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/restconfiguration/RestEditorTestIT.java
Labels: READY FOR MERGE

#1432 FUSETOOLS-3006: Prepare UI tests for Apache Camel Tooling (LSP)
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditor.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/SourceEditor.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelLSPCompletionTest.java
Labels: READY FOR MERGE

#1451 FUSETOOLS-3058 - deactivate "advanced source lookup"
  editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/launching/FuseMavenLaunchDelegate.java
Labels: PRIO, READY FOR MERGE

#1448 FUSETOOLS-3042: UI Tests - Create tests for REST page (editable mode)
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/RESTEditor.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/AddRESTOperationWizard.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RESTEditorAdvancedTest.java
Labels: REVIEW DONE

#1449 FUSETOOLS-3058 - code cleaning during investigation
  editor/plugins/org.fusesource.ide.launcher/META-INF/MANIFEST.MF
  editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourceLookupDirector.java
  editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourceLookupParticipant.java
  editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourcePathComputerDelegate.java
Labels: READY FOR MERGE

#1457 FUSETOOLS-3060 - fix issue with persisting rest editor changes
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
Labels: READY FOR MERGE, REVIEW DONE

#1456 FUSETOOLS-3059 - fix issue with unselectable / unmodifyable text fiel…
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
Labels: READY FOR MERGE, REVIEW DONE

#1458 FUSETOOLS-2945 - updating wsdl2rest version to get ID generation
  editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
Labels: READY FOR MERGE

#1454 FUSETOOLS-3002: Remove unused UI tests
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FeaturesServerTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FeaturesTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseProjectTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseProjectTestLong.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RegressionFuseTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RegressionTest.java
Labels: READY FOR MERGE
