Repository jbosstools/jbosstools-fuse, pull requests merged in 2018-07, with the labels that each got.

#1419 update the fallback for Fuse Online version to most recent GA version
  syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/IgniteVersionMapper.java
Labels: PRIO, READY FOR MERGE

#1420 FUSETOOLS-2992: UI Tests - Create tests for new 'wsdl2rest' wizard
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLAdvancedPage.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLFirstPage.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLWizard.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/wsdl2rest/WSDLFileEmpty.wsdl
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/wsdl2rest/WSDLFileExample.wsdl
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/wsdl2rest/WSDLFileInvalid.wsdl
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelRestDSLFromWSDLWizardTest.java
Labels: READY FOR MERGE, REVIEW DONE

#1422 FUSETOOLS-3029 - enabling Rest Element property page
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/rest/RestElementPropertiesSection.java
Labels: READY FOR MERGE

#1417 FUSETOOLS-3009 - replace Fuse Ignite with Fuse Online in UI
  configuration/ReadMe.md
  syndesis/plugins/org.fusesource.ide.syndesis.extension.core/OSGI-INF/l10n/bundle.properties
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/OSGI-INF/l10n/bundle.properties
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/l10n/messages.properties
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/README.MD
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/pom.xml
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/README.MD
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/pom.xml
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/README.MD
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/pom.xml
Labels: READY FOR MERGE

#1413 FUSETOOLS-2958: New UI test - Try to deploy all available templates to a runtime
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/config/deploymentTest-activemq.cfg
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DeploymentTest.java
Labels: READY FOR MERGE

#1428 FUSETOOLS-3017 - QuickstartsTest - Add check that Camel editor is not…
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/QuickStartsTest.java
Labels: READY FOR MERGE

#1429 FUSETOOLS-3043: Update UI tests to work with RedDeer 2.2
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
Labels: REVIEW DONE

#1430 FUSETOOLS-2749: Create bot test for canceling out of editing a global bean
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorBeanTest.java
Labels: READY FOR MERGE

#1434 FUSETOOLS-3023 - Add 6.3.0 R8 to available version
  configuration/camel2bom.properties
  configuration/camelVersionToDisplayName.properties
  core/features/org.fusesource.ide.core.feature/feature.xml
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/CamelForFuse6ToBomMapper.java
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630343/OSGI-INF/l10n/bundle.properties
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/.classpath
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/.project
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/.settings/org.eclipse.core.resources.prefs
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/.settings/org.eclipse.jdt.core.prefs
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/META-INF/MANIFEST.MF
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/OSGI-INF/l10n/bundle.properties
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/build.properties
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/plugin.xml
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/pom.xml
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2170redhat630347/src/org/fusesource/ide/camel/model/service/impl/v2170redhat630347/CamelCatalogWrapper.java
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
  core/plugins/pom.xml
Labels: READY FOR REVIEW

#1436 FUSETOOLS-3023 - set back online configuration file to master branch
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: READY FOR MERGE

#1440 FUSETOOLS-3023 - update plugin version in integration test
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/META-INF/MANIFEST.MF
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/META-INF/MANIFEST.MF
Labels: PRIO, READY FOR MERGE
