Repository jbosstools/jbosstools-fuse, pull requests merged in 2019-01, with the labels that each got.

#1501 FUSETOOLS-3085 - Restrict CBR and AMQ Template to 6.2 or 6.3R9+
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AMQTemplate.java
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/CBRTemplateForFuse6.java
  editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/impl/simple/AMQTemplateTest.java
  editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/impl/simple/CBRTemplateForFuse6Test.java
Labels: READY FOR REVIEW

#1500 FUSETOOLS-3179: Update RedDeer framework to 2.4.0
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
Labels: READY FOR MERGE

#1502 Lhein fusetools 3170 improvereadme
  configuration/ReadMe.md
Labels: READY FOR MERGE, REVIEW DONE

#1504 FUSETOOLS-3170 - Switch back config to master branch
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: READY FOR MERGE
