Repository jbosstools/jbosstools-fuse, pull requests merged in 2019-07, with the labels that each got.

#1543 FUSETOOLS-3231: UI Tests - Make tests independent of 'org.fusesource' dependencies
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/InstalledJREs.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
Labels: READY FOR MERGE, REVIEW DONE

#1548 FUSETOOLS-3239 - upgrade to Camel 2.23.2 internally
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
  core/plugins/org.fusesource.ide.camel.model.service.impl/.classpath
  core/plugins/org.fusesource.ide.camel.model.service.impl/META-INF/MANIFEST.MF
  core/plugins/org.fusesource.ide.camel.model.service.impl/build.properties
  core/plugins/org.fusesource.ide.camel.model.service.impl/pom.xml
  core/tests/org.fusesource.ide.camel.model.service.impl.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/internal/CamelServiceCatalogLoadingIT.java
Labels: READY FOR MERGE

#1555 FUSETOOLS-3244 - automatic switch perspective in tests
  jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/META-INF/MANIFEST.MF
  jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/src/org/fusesource/ide/jmx/camel/tests/integration/navigator/JMXNodesIT.java
Labels: READY FOR MERGE

#1554 FUSETOOLS-3252 - fix typos introducing in previous PR
  editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/ChangeCamelVersionJob.java
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorMoveIT.java
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/actions/SwitchCamelVersionIT.java
Labels: READY FOR MERGE

#1557 FUSETOOLS-3254 - avoid setting back the cursor to beginning when typing
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
Labels: READY FOR MERGE

#1560 FUSETOOLS-3255 - factorize code to always switch to debug perspective
  editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/AbstractRemoteCamelLaunchConfigurationDelegate.java
  editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java
  jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/src/org/fusesource/ide/jmx/camel/tests/integration/navigator/JMXNodesIT.java
Labels: READY FOR MERGE

#1564 FUSETOOLS-3245 - ensuring that we always insert a new rest
  core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelContextElement.java
Labels: READY FOR MERGE

#1567 FUSETOOLS-3257 - switch back to master for configuraion files
  core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
Labels: PRIO, READY FOR MERGE

#1561 FUSETOOLS-3260 - apply fixes to the internal camel catalog to work ar…
  core/plugins/org.fusesource.ide.camel.model.service.impl/src/org/fusesource/ide/camel/model/service/internal/CamelModelPatcher.java
Labels: READY FOR MERGE

#1563 FUSETOOLS-3263 - Adjust UI tests execution for CodeReady Studio 12.x
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml
Labels: READY FOR MERGE

#1566 FUSETOOLS-3266 - avoid potential NPE #1565
  editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java
Labels: READY FOR MERGE
