Repository jbosstools/jbosstools-fuse, pull requests merged in 2019-03, with the labels that each got.

#1508 FUSETOOLS-3185 - Avoid 0.9.0 which is introducing regression
  editor/plugins/org.fusesource.ide.project/META-INF/MANIFEST.MF
Labels: READY FOR REVIEW

#1512 Fusetools 3189 java11 compatibility2 attempt with all in same bundle
  editor/features/org.fusesource.ide.camel.editor.feature/feature.xml
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/.classpath
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/META-INF/MANIFEST.MF
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/build.properties
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/src/org/fusesource/ide/wsdl2rest/ui/wizard/Wsdl2RestWizard.java
  editor/plugins/org.fusesource.ide.wsdl2rest/.classpath
  editor/plugins/org.fusesource.ide.wsdl2rest/.project
  editor/plugins/org.fusesource.ide.wsdl2rest/.settings/org.eclipse.core.resources.prefs
  editor/plugins/org.fusesource.ide.wsdl2rest/.settings/org.eclipse.jdt.core.prefs
  editor/plugins/org.fusesource.ide.wsdl2rest/.settings/org.eclipse.m2e.core.prefs
  editor/plugins/org.fusesource.ide.wsdl2rest/META-INF/MANIFEST.MF
  editor/plugins/org.fusesource.ide.wsdl2rest/build.properties
  editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
  editor/plugins/pom.xml
Labels: READY FOR MERGE

#1513 FUSETOOLS-3191 - have internal project used for test java 11 compatible
  editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/resources/camel-context.xml
  editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/resources/jmx-pom.xml
Labels: READY FOR MERGE

#1518 Update Jacoco maven plugin to version 0.8.3
  pom.xml
Labels: PRIO, READY FOR REVIEW

#1517 FUSETOOLS-3200 - ignore jdk 11 warning
  core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/AbstractProjectCreatorRunnableIT.java
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
  syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/SyndesisExtensionProjectCreatorRunnableIT.java
Labels: READY FOR MERGE
