Repository jbosstools/jbosstools-fuse, pull requests merged in 2020-04, with the labels that each got.

#1603 FUSETOOLS-3332 - remove unused import package in test class
  editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-java-fuse6/src/test/java/com/mycompany/camel/RouteXmlTest.java
  editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-java-fuse7.1/src/test/java/com/mycompany/camel/RouteXmlTest.java
  editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-java-fuse7/src/test/java/com/mycompany/camel/RouteXmlTest.java
Labels: PRIO

#1607 FUSETOOLS-3333 - avoid NPE with UpdatevalueStrategy
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/validation/SyndesisExtensionIdValidator.java
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/validation/SyndesisExtensionNameValidator.java
  syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/validation/SyndesisExtensionVersionValidator.java
Labels: READY FOR REVIEW

#1601 FUSETOOLS-3320: Fix regex inside UI Tests to avoid failures on JDK11
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
Labels: REVIEW DONE

#1604 FUSETOOLS-3323: Update RedDeer framework to version 2.9.0
  uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
Labels: READY FOR MERGE, REVIEW DONE

#1605 FUSETOOLS-3331 - reactivate tests as webkit 2 is now availabel on CI
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorCheckOpeningInSpecialCasesIT.java
Labels: READY FOR REVIEW

#1615 FUSETOOLS-3340 - fix activeMQ dependency for SpringBoot
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntry.java
  editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntryDependenciesManager.java
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/provider/ToolBehaviourProviderIT.java
  editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntryTest.java
Labels: READY FOR REVIEW
