Repository jbosstools/jbosstools-fuse, pull requests merged in 2021-08, with the labels that each got.

#1698 FUSETOOLS-2500: UI Tests - Provide new UI test for choices properties…
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/PropertiesDropDownChoicesTest.java
Labels: READY FOR MERGE

#1701 FUSETOOLS-3472 - upgrade wsdl2rest.ui plugin for Fuse 7.9
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/.classpath
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml
Labels: READY FOR REVIEW

#1703 Fusetools 3497 fix jmx nodes with fuse 7.9
  servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/BaseConfigPropertyProvider.java
  servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/IConfigurationPropertyProvider.java
  servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xPortController.java
  servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/util/KarafUtils.java
  servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/java/org/fusesource/ide/server/karaf/core/server/subsystems/KarafUtilsJMXConnectionTest.java
  servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/resources/fake7_8/etc/org.apache.karaf.management.cfg
  servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/resources/fake7_8/etc/system.properties
  servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/resources/fake7_9/etc/org.apache.karaf.management.cfg
  servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/resources/fake7_9/etc/system.properties
Labels: READY FOR REVIEW

#1711 FUSETOOLS-3502 - fix compilation for compatibility with Target Platform
  editor/plugins/org.fusesource.ide.branding/META-INF/MANIFEST.MF
  editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/l10n/WizardMessages.properties
  editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelTestWizardPageOne.java
  editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/WizardMessages.java
Labels: READY FOR REVIEW, PRIO
