Repository jbosstools/jbosstools-fuse, pull requests merged in 2021-02, with the labels that each got.

#1651 FUSETOOLS2-977 - use conditional wait for checking Problems view
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProblemsViewTest.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/utils/FuseToolingProblems.java
Labels: READY FOR REVIEW

#1654 FUSETOOLS-3309 - workaround for StaleMutableRegistryException
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java
Labels: READY FOR REVIEW

#1653 FUSETOOLS2-979 - use specific name for test project for each tests
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/util/CamelMavenUtilsTestIT.java
Labels: READY FOR REVIEW

#1657 FUSETOOLS2-989 - use a specific name for each project test
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java
  editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/src/main/java/org/fusesource/ide/wsdl2rest/ui/tests/integration/AbstractWsdl2restWizardIT.java
  editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/src/main/java/org/fusesource/ide/wsdl2rest/ui/tests/integration/Wsdl2RestWizardForBlueprintIT.java
  editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/src/main/java/org/fusesource/ide/wsdl2rest/ui/tests/integration/Wsdl2RestWizardForSpringIT.java
  editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/src/main/java/org/fusesource/ide/wsdl2rest/ui/tests/integration/Wsdl2RestWizardIT.java
Labels: READY FOR REVIEW

#1662 FUSETOOLS2-978 - remove syncExec block to avoid potential jobs deadlock
  core/plugins/org.fusesource.ide.preferences/src/org/fusesource/ide/preferences/initializer/PreferencesInitializer.java
Labels: READY FOR REVIEW

#1659 FUSETOOLS2-990 - use different name for each project test
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/dataformat/wizards/NewDataFormatWizardIT.java
Labels: READY FOR REVIEW

#1665 JBDS-4912 - upgrade xmlbeans to 4.0.0
  pom.xml
  transformation/plugins/org.jboss.tools.fuse.transformation.core/.classpath
  transformation/plugins/org.jboss.tools.fuse.transformation.core/META-INF/MANIFEST.MF
  transformation/plugins/org.jboss.tools.fuse.transformation.core/build.properties
Labels: PRIO, READY FOR REVIEW

#1661 FUSETOOLS2-976 - use specific name for each test
  editor/tests/org.fusesource.ide.branding.tests.integration/src/main/java/org/fusesource/ide/branding/tests/integration/wizards/AbstractNewCamelTestWizardIT.java
Labels: READY FOR MERGE

#1664 FUSETOOLS2-991 - take screenshot on failure
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProviderIT.java
Labels: READY FOR MERGE

#1658 FUSETOOLS2-980 - put hs_err_pid files generated in a place that can be
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
Labels: READY FOR REVIEW

#1667 FUSETOOLS-3309 - provide more traces to catch StaleMutableProjectRegistryException root cause
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java
Labels: READY FOR MERGE

#1668 FUSETOOLS2-980 - backup workspace log for UI test failure
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DefaultTest.java
Labels: READY FOR MERGE

#1666 FUSETOOLS2-978 - fix PreferencesInitializer to access via UI Thread
  core/plugins/org.fusesource.ide.preferences/src/org/fusesource/ide/preferences/initializer/PreferencesInitializer.java
Labels: READY FOR MERGE

#1663 FUSETOOLS-3416 - close editor to avoid stacktrace in log
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/provider/ToolBehaviourProviderIT.java
Labels: READY FOR MERGE

#1670 FUSETOOLS2-991 - use first available shell if no active available
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProviderIT.java
Labels: REVIEW DONE

#1649 FUSETOOLS-3420 - replaced most uses of FuseProject rule to use empty default constructor to prevent project name duplication in integration tests
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/model/CamelElementConnectionIT.java
  core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/model/GlobalDefinitionsIT.java
  core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/test/util/editor/AbstractCamelEditorIT.java
  editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProviderIT.java
  editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/actions/SwitchCamelVersionIT.java
Labels: READY FOR REVIEW
