Repository jbosstools/jbosstools-fuse, pull requests merged in 2021-12, with the labels that each got.

#1741 FUSETOOLS-2589: UI Tests - Extend 'DownloadServerTest'
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DownloadServerTest.java
Labels: REVIEW DONE, READY FOR MERGE

#1744 FUSETOOLS-3596 - Upgrade AssertJ to 3.x
  core/tests/org.fusesource.ide.camel.validation.tests/META-INF/MANIFEST.MF
Labels: READY FOR REVIEW, PRIO

#1747 FUSETOOLS-3549 - Provide catalog cache for Fuse 7.10
  core/features/org.fusesource.ide.core.feature/feature.xml
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/.classpath
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/.project
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/META-INF/MANIFEST.MF
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/OSGI-INF/l10n/bundle.properties
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/build.properties
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/plugin.xml
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/pom.xml
  core/plugins/org.fusesource.ide.camel.model.service.impl.v2232fuse7_10_000020redhat00001/src/org/fusesource/ide/camel/model/service/impl/v2232fuse7_10_000020redhat00001/CamelCatalogWrapper.java
  core/plugins/pom.xml
Labels: READY FOR REVIEW

#1746 FUSETOOLS-3546 - upgrade wsdl2rest lib to Fuse 7.10
  editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml
Labels: READY FOR MERGE
