Repository jbosstools/jbosstools-fuse, pull requests merged in 2021-11, with the labels that each got.

#1730 FUSETOOLS-3492: UI Tests - fix flakiness in 'fuse-all > RouteManipula…
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RouteManipulationTest.java
Labels: REVIEW DONE, READY FOR MERGE

#1728 FUSETOOLS-3507: Fix UI tests issues related to JDK11 support in EAP/S…
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/SupportedCamelVersions.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
Labels: REVIEW DONE, PRIO, READY FOR MERGE

#1734 FUSETOOLS-3521: Convert fixed UI Test 'DefaultTest' into master branch
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DefaultTest.java
Labels: REVIEW DONE, READY FOR MERGE

#1732 FUSETOOLS-3401: UI Tests - Fix broken 'fuse-openshift' Jenkins job
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/OpenShiftRequirement.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/OpenShiftExplorer.java
  uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewOpenShiftConnectionWizard.java
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseOnOpenShiftTest.java
Labels: REVIEW DONE, READY FOR MERGE

#1735 FUSETOOLS-3491: UI Tests - Fix LSP UI tests flakiness in CamelEditorTest
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java
Labels: READY FOR REVIEW, PRIO

#1736 FUSETOOLS-3567 - Support Fuse 7.10 with java 11
  servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/BaseKarafStartupLaunchConfigurator.java
  servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf4xStartupLaunchConfigurator.java
Labels: READY FOR REVIEW

#1739 FUSETOOLS-3517: Verify and convert fixed UI Test 'ConfigurationsEdito…
  uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorEndpointTest.java
Labels: REVIEW DONE
